name: PUPSIS Grade Alert

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour, modify as u see fit : ) 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download previous-grades.json artifact
        uses: actions/download-artifact@v4
        with:
          name: grades-cache
        continue-on-error: true

      - name: Run script
        run: python scraper.py  # or main.py
        env:
          STUDNO: ${{ secrets.STUDNO }}
          BIRTH_MONTH: ${{ secrets.BIRTH_MONTH }}
          BIRTH_DAY: ${{ secrets.BIRTH_DAY }}
          BIRTH_YEAR: ${{ secrets.BIRTH_YEAR }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL: ${{ secrets.EMAIL }}

      - name: Upload updated previous-grades.json
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grades-cache
          path: previous-grades.json
