name: PUP Grade Watcher

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  run-script:
    name: Run PUP Grade Watcher
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore `.done` from cache
        id: cache-done
        uses: actions/cache@v4
        with:
          path: .done
          key: grade-done-main-${{ github.run_id }}
          restore-keys: |
            grade-done-main-

      - name: Check for `.done` file
        id: check_done
        run: |
          if [ -f ".done" ]; then
            echo "done=true" >> "$GITHUB_OUTPUT"
          else
            echo "done=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Skip if `.done` is present
        if: steps.check_done.outputs.done == 'true'
        run: echo "Grades already complete. Skipping."

      - name: Restore `previous-grades.json` from cache
        if: steps.check_done.outputs.done == 'false'
        id: cache-grades
        uses: actions/cache@v4
        with:
          path: previous-grades.json
          key: grade-previous-main-${{ github.run_id }}
          restore-keys: |
            grade-previous-main-

      - name: Set up Python
        if: steps.check_done.outputs.done == 'false'
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        if: steps.check_done.outputs.done == 'false'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run grade scraper
        if: steps.check_done.outputs.done == 'false'
        env:
          STUDNO: ${{ secrets.STUDNO }}
          BIRTH_MONTH: ${{ secrets.BIRTH_MONTH }}
          BIRTH_DAY: ${{ secrets.BIRTH_DAY }}
          BIRTH_YEAR: ${{ secrets.BIRTH_YEAR }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL: ${{ secrets.EMAIL }}
        run: python scraper.py

      - name: Save `.done` to cache
        if: steps.check_done.outputs.done == 'false' && success()
        uses: actions/cache@v4
        with:
          path: .done
          key: grade-done-main-${{ github.run_id }}

      - name: Save `previous-grades.json` to cache
        if: steps.check_done.outputs.done == 'false' && success()
        uses: actions/cache@v4
        with:
          path: previous-grades.json
          key: grade-previous-main-${{ github.run_id }}

      - name: Upload debug artifacts
        if: steps.check_done.outputs.done == 'false' && always()
        uses: actions/upload-artifact@v4
        with:
          name: grade-debug-artifacts
          path: |
            .done
            previous-grades.json
          retention-days: 1
