name: PUPSIS Grade Watcher

on:
  schedule:
    - cron: "0 * * * *"  # runs every hour
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check for .done file
        id: check_done
        run: |
          if [ -f ".done" ]; then
            echo "done=true" >> "$GITHUB_OUTPUT"
          else
            echo "done=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore previous grades cache
        uses: actions/cache@v4
        with:
          path: previous-grades.json
          key: grade-cache-main

      - name: Run script
        if: steps.check_done.outputs.done != 'true'
        run: python scraper.py
        env:
          STUDNO: ${{ secrets.STUDNO }}
          BIRTH_MONTH: ${{ secrets.BIRTH_MONTH }}
          BIRTH_DAY: ${{ secrets.BIRTH_DAY }}
          BIRTH_YEAR: ${{ secrets.BIRTH_YEAR }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL: ${{ secrets.EMAIL }}

      - name: Save updated grades cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: previous-grades.json
          key: grade-cache-main
